### ISSUE TITLE
nextItemFromIndex suffers off-by-one errors

### ISSUE THREAD

**Issue by NicholasBoll** [Bkucera/cypress-plugin-tab#13]
I found this issue hitting some edge cases in our CI (I assume timing related). On debugging I found an issue where the `nextItemFromIndex` function doesn't return the correct element if it comes to the end of a sequence (off by one error).

https://github.com/Bkucera/cypress-plugin-tab/blob/master/src/index.js#L76-L94

```ts
const seq = [1, 2, 3, 4];

const nextItem = nextItemFromIndex(3, seq, false);
console.log(nextItem); // undefined

const previousItem = nextItemFromIndex(0, seq, true);
console.log(nextItem); // undefined
```

What happens is 3 is _not_ the length of the array, so the  `if (i === seq.length)` is not true. Even if it was, the logic is still wrong, it would have to set `i = -1` instead, because `i` is getting incremented.

The correct implementation should be:
```ts
const nextItemFromIndex = (i, seq, reverse) => {
  let nextIndex;
  if (reverse) {
    nextIndex = i - 1;
    if (nextIndex < 0) {
      nextIndex = seq.length - 1;
    }
  } else {
    nextIndex = i + 1;
    if (nextIndex === seq.length) {
      nextIndex = 0;
    }
  }
  return seq[nextIndex];
}
```

Or a bit more succinct:
```ts
const nextItemFromIndex = (i, seq, reverse) => {
  if (reverse) {
    const nextIndex = i === 0 ? seq.length - 1 : i - 1;
    return seq[nextIndex];
  } else {
    const nextIndex = i === seq.length - 1 ? 0 : i + 1;
    return seq[nextIndex];
  }
}
```

**Comment by Bkucera** [comment]
thanks @NicholasBoll , I'll accept a PR or fix it when I have time

**Comment by NicholasBoll** [comment]
I'm opening a pull request soon for this with 2 tests
