### ISSUE TITLE
Cypress v4.x Support

### ISSUE THREAD

**Issue by TheWanderingWalnut** [Bkucera/cypress-plugin-tab#20]
Cypress has updated to version 4.x.x, which will require this plugin to update its dependencies in order to maintain compatibility with the current version. Thank you!

**Comment by TheWanderingWalnut** [comment]
Thanks for the quick update!

**Comment by Bkucera** [comment]
fixed in https://github.com/Bkucera/cypress-plugin-tab/commit/b476b0a888481fdd0dd6be7fcac0abac125c931d
