### ISSUE TITLE
cy.tab executes too quickly

### ISSUE THREAD

**Issue by NicholasBoll** [Bkucera/cypress-plugin-tab#4]
I ran into an edge case where `cy.tab()` happens too fast. You can actually witness this while watching the GUI. If you `cy.tab().tab()`, you can't see focus changing. If I added a `cy.wait()`, I could see focus changing.

I'm building an accessible modal for github.com/Workday/canvas-kit: Workday/canvas-kit#59. Our Accessibility Specialists want the header to receive focus when the modal opens if there is no close icon (a config option for modals). That header should not be focusable again (removes the tabIndex on blur). `cy.tab` executes so fast that the DOM doesn't have time to reflect this change (since there is no wait between tabs). The `blur` fires and the tabIndex attribute is removed, but the DOM isn't updated by the time the next Cypress command runs.

Adding a wait for a single frame (using `requestAnimationFrame`) solves this issue where `focus` or `blur` events are allowed to execute and the DOM has been updated before continuing. This change also allows the focus ring to visibly change while the test is running.

Some other commands either wait 50ms or use https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/actionability.coffee

I can override `tab` in my support file to force a wait to fix this, but perhaps this will cause issues for other people.

**Comment by NicholasBoll** [comment]
Without modifying source code, the following works:

```js
import 'cypress-plugin-tab';

Cypress.Commands.overwrite('tab', (originalFn, subject) => {
  const raf = () => new Cypress.Promise(resolve => {
    cy.state('window').requestAnimationFrame(resolve);
  });

  return raf().then(() => {
    return originalFn(subject);
  });
});

```

**Comment by Bkucera** [comment]
Thanks @NicholasBoll, I'll work on getting this in a PR

**Comment by NicholasBoll** [comment]
I could do a PR as well, unless you have a different approach.

**Comment by NicholasBoll** [comment]
Woot! All specifications pass without command overrides!
