### ISSUE TITLE
cy.tab returns `undefined` if keydown was cancelled

### ISSUE THREAD

**Issue by NicholasBoll** [Bkucera/cypress-plugin-tab#5]
This may or may not be an actual issue. I'm not sure the intent.

I'm creating a modal with a focus trap. The way the focus trap works is it will cancel the keydown event if focus will travel outside the trap. `cy.tab` will return an empty subject in this case even if the focus lands somewhere:

https://github.com/Bkucera/cypress-plugin-tab/blob/ebce91c3d6ff8399e11f1f26a559588e4d1779ce/src/index.js#L122-L135

`onCancel` is defined as `_.noop` here:
https://github.com/Bkucera/cypress-plugin-tab/blob/ebce91c3d6ff8399e11f1f26a559588e4d1779ce/src/index.js#L67

From my experiments, I could change the `_.noop` to be a function that returns the `activeElement` of the document. This works:

```js
  const simulatedCancel = () => {
    // Perhaps a focus trap cancelled? Return the activeElement
    return cy.now('focus', cy.$$(doc.activeElement));
  };

  return Promise.try(() => {
    return keydown(activeElement, options, simulatedDefault, simulatedCancel);
  }).finally(() => {
    keyup(activeElement, options);
  });
```

I see that `newElm.focus()` was actually commented out... It made me think, why is `tabsequence` even needed? Can we just always send the correct key events and just always return the new `doc.activeElement` whatever that might be? This would allow support for `tabIndex=-1` which is currently not supported (because the element doesn't exist in the tabsequence), but works in the browser regardless.

**Comment by NicholasBoll** [comment]
> I see that `newElm.focus()` was actually commented out... It made me think, why is `tabsequence` even needed? Can we just always send the correct key events and just always return the new `doc.activeElement` whatever that might be? This would allow support for `tabIndex=-1` which is currently not supported (because the element doesn't exist in the tabsequence), but works in the browser regardless.

Nevermind. I see that `cy.now('focus', cy.$$(doc.activeElement));` is what does the focusing.

**Comment by NicholasBoll** [comment]
I guess another implementation could be simply:

```js
  return Promise.try(() => {
    keydown(activeElement, options, simulatedDefault, _.noop);
    return doc.activeElement;
  }).finally(() => {
    keyup(activeElement, options);
  });
```

**Comment by NicholasBoll** [comment]
Without this change, a workaround is:

```js
import 'cypress-plugin-tab';

Cypress.Commands.overwrite('tab', (originalFn, subject) => {
  originalFn(subject).then(s => s || cy.state('window').document.activeElement)
});
```

OR with the `requestAnimationFrame` waiting added in:

```js
import 'cypress-plugin-tab';

const raf = () =>
  new Cypress.Promise(resolve => {
    cy.state('window').requestAnimationFrame(resolve);
  });

Cypress.Commands.overwrite('tab', (originalFn, subject) => {
  return raf().then(() =>
    originalFn(subject).then(s => s || cy.state('window').document.activeElement)
  );
});
```

**Comment by Bkucera** [comment]
@NicholasBoll feel free to review #9

**Comment by Bkucera** [comment]
@NicholasBoll

**Comment by NicholasBoll** [comment]
You're too fast. I was just writing about this: https://github.com/NicholasBoll/blog/blob/master/contents/articles/cypress-tab-plugin/index.md#tab-key-inside-a-focus-trap
